chore: set task sha for `fetch-product-metadata` (#887)
* chore: set task sha for `fetch-product-metadata`

Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>

* chore: establish `common-base.yaml`

Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>

* fix: silence grep error to allow error handling

Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>

---------

Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>

diff --git a/tasks/fetch-product-metadata/fetch-product-metadata.yaml b/tasks/fetch-product-metadata/fetch-product-metadata.yaml
--- a/tasks/fetch-product-metadata/fetch-product-metadata.yaml
+++ b/tasks/fetch-product-metadata/fetch-product-metadata.yaml
@@ -43,10 +43,10 @@ spec:
         fi
 
         echo "* Extracting image repository"
-        output_image_repo=$(echo "${OUTPUT_IMAGE}" | grep -oE '[a-z0-9-]+-(acm|mce)-[0-9]+')
+        output_image_repo=$(echo "${OUTPUT_IMAGE}" | grep -oE '[a-z0-9-]+-(acm|mce)-[0-9]+' || true)
         echo "  Image repository: '${output_image_repo}'"
         if [[ -z ${output_image_repo} ]]; then
-          echo "error: failed to parse image repository from image '${OUTPUT_IMAGE}'" >&2
+          echo "error: failed to parse ACM or MCE image repository from image '${OUTPUT_IMAGE}'" >&2
           exit 1
         fi
         echo "* Extracting component"
